name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: List build output
        run: ls -la dist/rakium-dev/browser/

      - name: Copy CNAME
        run: cp src/assets/CNAME dist/rakium-dev/browser/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/rakium-dev/browser
          cname: rakium.dev
          commit_message: "Deploy to GitHub Pages"
          force_orphan: true 